package org.drools.event;

import java.util.Collection;

import org.drools.definition.KnowledgePackage;
/* An event that is generated by Knowledge Source*/
public class KnowledgeEvent {

	private Collection<KnowledgePackage> kpkg;
	/*Instantiating Knowledge Event*/
	public KnowledgeEvent(Collection<KnowledgePackage> kp) {
		this.kpkg = kp;
	}
	
	/*
	getting the knowledgepackage to be updated to current KnowledgeBase
	returns Collection of KnowledgePackage
	*/
	public Collection<KnowledgePackage> getKpkg() {
		return kpkg;
	}
	
	public void setKpkg(Collection<KnowledgePackage> kpkg) {
		this.kpkg = kpkg;
	}

}
